### ISSUE TITLE
some troubles on request send

### ISSUE THREAD

**Issue by EvvC** [herooutoftime/ajenti-letsencrypt#12]
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 161, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(**(params or {}))
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 230, in request_button
    self.request_certificates()
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 198, in request_certificates
    p = subprocess.Popen(params, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/pymodules/python2.7/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 534, in __init__
    reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 503, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 1253, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by shu006** [comment]
i am also getting this error

**Comment by keval-gangani** [comment]
I'm getting same error. When you apply fix on this plugin?

**Comment by JintoAntony** [comment]
Looks like he is not maintaining this repo anymore. I have the same issue on Debian server.
