### ISSUE TITLE
Request error on fresh install

### ISSUE THREAD

**Issue by bbbenji** [herooutoftime/ajenti-letsencrypt#3]
I am testing out this plugin on a fresh install of Ajenti + Ajenti-V on Debian and receive the following error when I attempt to request a new cert.

`[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(**(params or {}))
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 230, in request_button
    self.request_certificates()
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 198, in request_certificates
    p = subprocess.Popen(params, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/pymodules/python2.7/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 534, in __init__
    reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 503, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 1253, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by herooutoftime** [comment]
Hi @bbbenji,
there were some issues with the name of the plugin `ajenti-letsencrypt` which lead to unexpected behaviour or even the complete lack of it in Ajenti. README was just updated by @jBOKA. Hope that helps.

**Comment by bbbenji** [comment]
@herooutoftime Thanks for taking the time to reply, though I have already renamed the directory to `letsencrypt` before I was able to see the plugin in Ajenti.

**Comment by kamilkrzeminski** [comment]
@bbbenji I have the same issue on Ubuntu 14.04. Installed Letsencrypt from ppa:certbot/certbot. 
I supposed that paths specified are wrong, I've never seen /etc/letsencrypt.sh/ before.
I tried changing it to /etc/letsencrypt. Files 'config' and 'domains.txt' were created inside /etc/letsencrypt, but the error is still showing.
