### ISSUE TITLE
request not working

### ISSUE THREAD

**Issue by Shtepin** [herooutoftime/ajenti-letsencrypt#8]
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(**(params or {}))
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 230, in request_button
    self.request_certificates()
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 198, in request_certificates
    p = subprocess.Popen(params, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/pymodules/python2.7/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 238, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 755, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ronfak** [comment]
I have the exact same problem here :

```
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(**(params or {}))
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 230, in request_button
    self.request_certificates()
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 198, in request_certificates
    p = subprocess.Popen(params, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/pymodules/python2.7/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by herooutoftime** [comment]
@Shtepin @ronfak 
I will look into this asap and come back to you with some information

**Comment by Roboroads** [comment]
I'm having this exact same issue after clicking request,

**Comment by spoudazon** [comment]
Had the same issue.
It's because of that that directory is empty: letsencrypt/libs/letsencrypt.sh/

**Comment by abdulwahabkdi** [comment]
Hello,

I have the same error on Ubuntu 16.04
---------------------
```
07.08.2017 04:50 compat.py:20                  DEBUG [root] Popen: ['/var/lib/ajenti/plugins/letsencrypt/libs/letsencrypt.sh/letsencrypt.sh', '-c', '--force']
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(**(params or {}))
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 230, in request_button
    self.request_certificates()
  File "/var/lib/ajenti/plugins/letsencrypt/main.py", line 198, in request_certificates
    p = subprocess.Popen(params, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/pymodules/python2.7/ajenti/compat.py", line 26, in Popen
    *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 534, in __init__
    reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 503, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python2.7/dist-packages/gevent/subprocess.py", line 1253, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
07.08.2017 04:50 compat.py:20                  DEBUG [root] Popen: ['uname', '-mp']
```
---------------------

I used the command "git clone https://github.com/herooutoftime/ajenti-letsencrypt.git letsencrypt"
The certificate request from Ajenti panel is failing.

@herooutoftime Do you have any update on this?.

Thanks
Abdul

**Comment by fernandovrgas** [comment]
Hi,

someone solved this problem? Now i have de same problem here

**Comment by fromage9747** [comment]
The file just doesn't exist.  The fix would be to find the letsencrypt.sh script and chuck it in the folder.  I have not been able to find it as of yet but only spent the last ten minutes searching for it.

**Comment by JintoAntony** [comment]
I have this issue on my Debian server.  Any one solved this ..? All folders exist.

**Comment by fromage9747** [comment]
Couldn't solve it. I ended up using let's encrypt through terminal instead.
